{"name": "test_valid_credentials_1", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <regular.tests.test_selenium_elemental.TestLogin object at 0x107f17d90>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"5251cf33ebe51bf9ecba7625e95d053d\")>\n\n    @pytest.fixture\n    def login(self, driver):\n>       return login_page.LoginPage(driver)\n\ntests/test_selenium_elemental.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <regular.pages.login_page.LoginPage object at 0x107f17dd0>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"5251cf33ebe51bf9ecba7625e95d053d\")>\n\n    def __init__(self, driver):\n        self.driver = driver\n        self._visit(\"/login\")\n>       assert self._is_displayed(self._login_form)\nE       AssertionError\n\npages/login_page.py:16: AssertionError"}, "start": 1614289417544, "stop": 1614289417544, "uuid": "6792c617-b935-4b18-a2a3-44f7a43203da", "historyId": "63495afdb3a59b82783c91588cdc2e1c", "testCaseId": "1436dd9f55e1ab3de571e6d6d8a7a876", "fullName": "tests.test_selenium_elemental.TestLogin#test_valid_credentials_1", "labels": [{"name": "tag", "value": "shallow"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_selenium_elemental"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "C07ZQ0G3JYVX"}, {"name": "thread", "value": "90508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_selenium_elemental"}]}