{"name": "test_invalid_credentials", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <regular.tests.test_selenium_elemental.TestLogin object at 0x107e8d3d0>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"7f2f73d88a62fe54ec01bde1fe22f56d\")>\n\n    @pytest.fixture\n    def login(self, driver):\n>       return login_page.LoginPage(driver)\n\ntests/test_selenium_elemental.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <regular.pages.login_page.LoginPage object at 0x107e8d890>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"7f2f73d88a62fe54ec01bde1fe22f56d\")>\n\n    def __init__(self, driver):\n        self.driver = driver\n        self._visit(\"/login\")\n>       assert self._is_displayed(self._login_form)\nE       AssertionError\n\npages/login_page.py:16: AssertionError"}, "start": 1614289419897, "stop": 1614289419897, "uuid": "879cbf08-0755-4e5d-8079-9e7ebe339621", "historyId": "86ad78a0467df1272de2c4fd74b60359", "testCaseId": "41e58c561d5688154911440bf1b9ae09", "fullName": "tests.test_selenium_elemental.TestLogin#test_invalid_credentials", "labels": [{"name": "tag", "value": "deep"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_selenium_elemental"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "C07ZQ0G3JYVX"}, {"name": "thread", "value": "90508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_selenium_elemental"}]}