{"name": "test_invalid_credentials", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <regular.tests.test_selenium_elemental.TestLogin object at 0x10a449ed0>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"ab69c1f095f23ec7d8bbc84d26fb93d3\")>\n\n    @pytest.fixture\n    def login(self, driver):\n>       return login_page.LoginPage(driver)\n\nregular/tests/test_selenium_elemental.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <regular.pages.login_page.LoginPage object at 0x10a4b58d0>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"ab69c1f095f23ec7d8bbc84d26fb93d3\")>\n\n    def __init__(self, driver):\n        self.driver = driver\n        self._visit(\"/login\")\n>       assert self._is_displayed(self._login_form)\nE       AssertionError\n\nregular/pages/login_page.py:16: AssertionError"}, "start": 1614289501105, "stop": 1614289501105, "uuid": "44eece8e-fdd5-4866-aa7b-5fba361fdfd7", "historyId": "79e29aaca4b797595149f4df6880024c", "testCaseId": "2db80e7d18d20fab5703b98b26c1e104", "fullName": "regular.tests.test_selenium_elemental.TestLogin#test_invalid_credentials", "labels": [{"name": "tag", "value": "deep"}, {"name": "parentSuite", "value": "regular.tests"}, {"name": "suite", "value": "test_selenium_elemental"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "C07ZQ0G3JYVX"}, {"name": "thread", "value": "90572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "regular.tests.test_selenium_elemental"}]}